services:
  - type: web
    name: fakestackoverflow-backend
    env: node
    region: oregon # or choose a region closer to your users
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
      - key: JWT_SECRET
        generateValue: true # Generate a random value on first deploy
      - key: MONGODB_URI
        sync: false # You'll need to manually set this in the Render dashboard
    autoDeploy: true
    
  - type: web
    name: fakestackoverflow-frontend
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build # Adjust if your build outputs to a different directory
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          name: fakestackoverflow-backend
          type: web
          property: url
